[programs.localnet]
anchor_escrow = "2vBPiP2vLEpSH3HoMy3KzRB1UWu3EViTjQQQhK6W3EDk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://rpc-mainnet-fork.dappio.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
